### ISSUE TITLE
sui: write HelloToken example

### ISSUE THREAD

**Issue by gator-boi** [wormhole-foundation/wormhole-scaffolding#28]
Objective
Write HelloToken example based on the [Hello Token](https://github.com/wormhole-foundation/wormhole-scaffolding/tree/main/evm/src/02_hello_token) specification.

Definition of Done
Write smart contract based on whitepaper spec. Add supporting unit tests, integration tests, and deployment scripts.

**Comment by aadam-10** [comment]
work may continue in https://github.com/wormhole-foundation/wormhole-scaffolding/issues/41
